name: Export Size

on:
    pull_request:
        branches:
            - dev

jobs:
    size:
        runs-on: ubuntu-latest
        env:
            CI_JOB_NUMBER: 1
        steps:
            - uses: actions/checkout@v3
            - uses: antfu/export-size-action@main
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  paths: packages/core,packages/shared,packages/integrations
